"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _

import os
from dotenv import load_dotenv

load_dotenv() # Սա կարդում է .env ֆայլը

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Security
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',  # <--- ԱՎԵԼԱՑՐՈՒ ԱՅՍ ՏՈՂԸ
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.context_processors.subjects_processor',
                'myapp.context_processors.global_forms',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_LANGUAGES = ('en', 'hy', 'ru')

# Նախնական լեզուն (եթե ուզում ես հայերենը լինի հիմնական, գրիր 'hy')
LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_TZ = True

USE_I18N = True

# Հասանելի լեզուների ցանկը
LANGUAGES = [
    ('en', _('English')),
    ('hy', _('Armenian')),
    ('ru', _('Russian')),
]

# Որտեղ են պահվելու թարգմանությունների ֆայլերը
import os
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale/'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'myapp/static'] # Սա ասում է Django-ին, որ static ֆայլերը այստեղ են

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CKEDITOR_CONFIGS = {
    'default': {
        'width': 'auto',  # ԱՅՍ ՏՈՂՆ Է ԼՈՒԾՈՒՄ ԽՆԴԻՐԸ
        'height': 300,    # Կարող ես բարձրությունն էլ կարգավորել, որ շատ մեծ չլինի
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
            ['Image', 'Table', 'HorizontalRule'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor']
        ],
    }
}

JAZZMIN_SETTINGS = {
    # Վերևի մենյուի կարգավորումներ
    "topmenu_links": [
        # Հղում դեպի գլխավոր էջ (կբացվի նոր պատուհանով)
        {"name": "Դիտել Կայքը",  "url": "/", "new_window": True},
        # Կարող ես նաև կոնկրետ մոդելի արագ հղում դնել վերևում
        {"model": "auth.User"},
    ],

    # Բրաուզերի tab-ի վրա երևացող վերնագիրը
    "site_title": "Aram's Portfolio Admin",

    # Վերնագիր, որը երևում է լոգին լինելու էջում
    "site_header": "Portfolio Admin",

    # Կողային մենյուի վերևում երևացող գլխավոր անվանումը
    "site_brand": "Aram Code Lab",

    # Բարի գալուստի տեքստը լոգինի էջում
    "welcome_sign": "Բարի գալուստ Կառավարման Վահանակ",

    # Հեղինակային իրավունքի նշումը պանելի ամենաներքևում
    "copyright": "Created By Aram",

    # Եթե ունես լոգո քո static թղթապանակում, կարող ես ակտիվացնել այս տողը և նշել ուղին
    "site_logo": "images/unnamed.png",

    # Հետաքրքիր ֆիքս. թույլ է տալիս կողային մենյուն պահել բաց կամ փակ
    "navigation_expanded": True,

    # Ակտիվացնում է Pop-up պատուհանները
    "related_modal_active": True,

    "changeform_format": "single",

    # Այքոններ հավելվածների և մոդելների համար
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        # Փոխարինիր myapp-ը քո հավելվածի անունով
        "myapp.Project": "fas fa-briefcase", # Պորտֆոլիոյի նշան
        "myapp.Subject": "fas fa-book",      # Գրքի նշան առարկաների համար
        "myapp.Material": "fas fa-file-alt", # Ֆայլի նշան նյութերի համար
    },
    # Եթե մոդելը չունի նշված այքոն, կդնի այս ստանդարտը
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "custom_css": "css/admin_custom.css",
}

# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Այն թղթապանակը, որտեղ կհավաքվեն բոլոր CSS/JS-ները
#STATIC_ROOT = BASE_DIR / 'staticfiles'


# settings.py

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}