# Generated by Django 6.0.4 on 2026-04-20 18:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
        migrations.RemoveField(
            model_name='material',
            name='link',
        ),
        migrations.AddField(
            model_name='material',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
