# Generated by Django 6.0.4 on 2026-04-21 08:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_project_created_at_material_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='content_hy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='title_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_hy',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
